services:
  nginx:
    image: nginx  #image name
    container_name: nginx
    env_file: .env
    build: requirements/nginx/. #path to Dockerfile
    ports:
      - "443:443"
    restart: always

  mariadb:
    image: mariadb
    container_name: mariadb
    env_file: .env
    build: requirements/mariadb/.
    ports:
      - "3306"
    restart: always

  wordpress:
    container_name: wordpress
    env_file: .env
    build: requirements/wordpress/.
    restart: always
    depends_on:
      - mariadb