networks:
  inception:
    driver: bridge # Create a private internal network using the bridge driver

volumes:
  mariadb:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yusengok/data/db
  
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yusengok/data/wordpress

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb/.
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql # path to the volume
    networks:
      - inception
    expose:
      - "3306"
    restart: unless-stopped

  wordpress:
    image: wordpress
    container_name: wordpress
    build: requirements/wordpress/.
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: on-failure
    depends_on:
      - mariadb # Wordpress starts after mariadb
    expose:
      - "9000"
    #user: "www-data"

  nginx:
    image: nginx  # image name
    container_name: nginx
    build: requirements/nginx/.
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    depends_on:
      - wordpress # Nginx starts after wordpress
    ports:
      - "443:443"
    restart: on-failure
