services:

  mariadb:
    image: mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql # path to the volume
    networks:
      - inception
    build: 
      context: requirements/mariadb/
      dockerfile: Dockerfile
      args:
        - SQL_DATABASE=${SQL_DATABASE}
        - SQL_USER=${SQL_USER}
        - SQL_PASSWORD=${SQL_PASSWORD}
        - SQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
    expose:
      - "3306"
    restart: unless-stopped

  wordpress:
    image: wordpress
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: requirements/wordpress/.
    restart: on-failure
    depends_on:
      - mariadb # Wordpress starts after mariadb
    expose:
      - "9000"
    #user: "www-data"

  nginx:
    image: nginx  # image name
    container_name: nginx
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress # Nginx starts after wordpress
    build: requirements/nginx/.
    ports:
      - "443:443"
    restart: on-failure

volumes:
  mariadb:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yusengok/data/db
  
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yusengok/data/wordpress

networks:
  inception:
    driver: bridge # Create a private internal network using the bridge driver