services:
  nginx:
    image: nginx  #image name
    container_name: nginx
    env_file: .env
    build: requirements/nginx/. #path to Dockerfile
    ports:
      - "443:443"
    restart: always

  mariadb:
    image: mariadb
    container_name: mariadb
    env_file: .env
    build: requirements/mariadb/.
    ports:
      - "3307:3306"
    restart: always
