version: "3.8"

# sudo docker-compose -f ./srcs/docker-compose.yml up -d --build

services:
  nginx:
    image: nginx  #image name
    container_name: nginx
    build: requirements/nginx/. #path to Dockerfile
    ports:
      - "443:443"
    restart: on-failure
