networks:
  inception:
    driver: bridge # Create a private internal network using the bridge driver

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yusengok/data/mariadb
  
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yusengok/data/wordpress

  website:
    name: website
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yusengok/data/website

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb/.
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql # path to the volume
    networks:
      - inception
    expose:
      - "3306"
    restart: unless-stopped

  wordpress:
    image: wordpress
    container_name: wordpress
    build: requirements/wordpress/.
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: on-failure
    depends_on:
      - mariadb # Wordpress starts after mariadb

  nginx:
    image: nginx  # image name
    container_name: nginx
    build: requirements/nginx/.
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
      - website:/var/www/resume
    networks:
      - inception
    depends_on:
      - wordpress
      - website
    ports:
      - "443:443"
    restart: on-failure
  
  adminer:
    image: adminer
    container_name: adminer
    build: requirements/bonus/adminer/.
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
    restart: on-failure

  redis:
    image: redis
    container_name: redis
    build: requirements/bonus/redis/.
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    restart: on-failure

  ftp:
    image: ftp
    container_name: ftp
    build: requirements/bonus/ftp/.
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "20:20"
      - "21:21"
      - "40000-40005:40000-40005"
    restart: on-failure

  website:
    image: website
    container_name: website
    build: requirements/bonus/website/.
    volumes:
      - website:/var/www/resume
    networks:
      - inception
    restart: on-failure
    expose:
      - "8080"

  fail2ban:
    image: fail2ban
    container_name: fail2ban
    build: requirements/bonus/fail2ban/.
    volumes:
      - /var/log/auth.log:/var/log/auth.log # For ssh
      - /var/log/nginx/error.log:/var/log/nginx/error.log # For nginx
      - /var/log/vsftpd.log:/var/log/vsftpd.log # For mariadb
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - nginx
      - wordpress
      - ftp
    restart: on-failure